$(function()
{
  $('#ticker_1').cryptoticker();
  $('#ticker_2').cryptoticker({
    startIndex:0,
    getTopCoins:20,
    nameColor:'yellow',
    separatorColor:'#ddd',
    priceColor:'orange',
    speed:5000
  });
})
